// Shared PGlite harness for Email Marketing V1 tests from Increment 3a on.
// (Increment 1-2 suites keep their own copies and are intentionally untouched.)
//
// PGlite is intentionally not a project dependency; callers run under an
// ephemeral `npx -y -p @electric-sql/pglite node ...`.

import { readText } from "./email_marketing_v1_migration_order.mjs";
import { createRequire } from "node:module";
import { delimiter, dirname, join, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));

export async function loadPGlite() {
  try {
    return await import("@electric-sql/pglite");
  } catch {
    for (const dir of (process.env.PATH || "").split(delimiter)) {
      if (!dir.includes("_npx")) continue;
      try {
        const require = createRequire(join(dir, "..", "noop.js"));
        return await import(pathToFileURL(require.resolve("@electric-sql/pglite")).href);
      } catch {
        // try the next PATH entry
      }
    }
  }
  throw new Error("PGlite not found. Run with: npx -y -p @electric-sql/pglite node <file>");
}

export const MIGRATIONS = {
  inc1: resolve(here, "../migrations/20260926160000_email_marketing_v1_foundation.sql"),
  inc2: resolve(here, "../migrations/20260927120000_email_marketing_v1_audiences.sql"),
  // EMAIL_INC3A_MIGRATION_PATH exists only for the mutation runner.
  inc3a: process.env.EMAIL_INC3A_MIGRATION_PATH
    || resolve(here, "../migrations/20261004150000_email_marketing_v1_senders_templates.sql"),
};
export const RECOVERY_INC3A = resolve(here, "../recovery/20261004150000_email_marketing_v1_senders_templates.down.sql");
// Line-ending independent (see readText in email_marketing_v1_migration_order.mjs).
export const readSql = (path) => readText(path);

export const ORG_A = "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa";
export const ORG_B = "bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb";
export const A_FOUNDER = "a0000000-0000-4000-8000-000000000001";
export const A_ADMIN = "a0000000-0000-4000-8000-000000000002";
export const A_LEAD = "a0000000-0000-4000-8000-000000000003";
export const A_MEMBER = "a0000000-0000-4000-8000-000000000004";
export const B_FOUNDER = "b0000000-0000-4000-8000-000000000001";
export const NO_ORG = "d0000000-0000-4000-8000-000000000001";

// Minimal Supabase shim (roles, auth.uid(), broad default privileges like
// Supabase) plus two tenants with every membership role.
export async function createDatabase() {
  const { PGlite } = await loadPGlite();
  const db = new PGlite();
  await db.exec(`
    create role anon nologin;
    create role authenticated nologin;
    create role service_role nologin bypassrls;
    grant anon, authenticated, service_role to current_user;
    grant usage on schema public to anon, authenticated, service_role;
    alter default privileges in schema public grant all on tables to anon, authenticated, service_role;
    alter default privileges in schema public grant all on sequences to anon, authenticated, service_role;
    alter default privileges in schema public grant execute on functions to anon, authenticated, service_role;

    create schema auth;
    create schema private;
    create table auth.users (id uuid primary key);
    create function auth.uid() returns uuid language sql stable as $$
      select nullif(current_setting('request.jwt.claim.sub', true), '')::uuid
    $$;
    grant usage on schema auth to anon, authenticated, service_role;
    grant execute on function auth.uid() to anon, authenticated, service_role;

    create table public.organizations (id uuid primary key, name text not null);
    create table public.organization_memberships (
      user_id uuid not null references auth.users(id) on delete cascade,
      organization_id uuid not null references public.organizations(id) on delete cascade,
      role text not null check (role in ('founder', 'admin', 'area_lead', 'member')),
      primary key (user_id, organization_id)
    );
    create table public.user_active_organizations (
      user_id uuid primary key references auth.users(id) on delete cascade,
      organization_id uuid not null,
      foreign key (user_id, organization_id)
        references public.organization_memberships(user_id, organization_id) on delete cascade
    );
    create function public.current_user_organization_id()
    returns uuid language sql stable security definer set search_path = '' as $$
      select active.organization_id
      from public.user_active_organizations as active
      join public.organization_memberships as membership
        on membership.user_id = active.user_id
       and membership.organization_id = active.organization_id
      where active.user_id = (select auth.uid());
    $$;
    create table public.clients (
      id bigint generated by default as identity primary key,
      organization_id uuid not null references public.organizations(id),
      company_name text not null,
      contact_name text,
      email text
    );

    insert into auth.users(id) values ('${A_FOUNDER}'), ('${A_ADMIN}'), ('${A_LEAD}'), ('${A_MEMBER}'), ('${B_FOUNDER}'), ('${NO_ORG}');
    insert into public.organizations(id, name) values ('${ORG_A}', 'A'), ('${ORG_B}', 'B');
    insert into public.organization_memberships(user_id, organization_id, role) values
      ('${A_FOUNDER}', '${ORG_A}', 'founder'), ('${A_ADMIN}', '${ORG_A}', 'admin'),
      ('${A_LEAD}', '${ORG_A}', 'area_lead'), ('${A_MEMBER}', '${ORG_A}', 'member'),
      ('${B_FOUNDER}', '${ORG_B}', 'founder');
    insert into public.user_active_organizations(user_id, organization_id) values
      ('${A_FOUNDER}', '${ORG_A}'), ('${A_ADMIN}', '${ORG_A}'), ('${A_LEAD}', '${ORG_A}'),
      ('${A_MEMBER}', '${ORG_A}'), ('${B_FOUNDER}', '${ORG_B}');
  `);
  return db;
}

// Same function lists and fingerprint algorithm as the Staging acceptance
// runner (supabase/tests/acceptance/email_marketing_v1_inc1_inc2_human_acceptance.sql).
export const INC1_NAMES = ["email_normalize_address", "email_address_hash", "email_can", "email_require",
  "email_reject_mutation", "email_contacts_guard", "email_contact_consents_guard", "email_suppressions_guard",
  "email_write_audit", "email_is_sendable", "email_clean_name", "email_clean_locale", "email_clean_timezone",
  "email_request_hash", "email_add_suppression", "email_archive_contact", "email_create_contact",
  "email_lift_suppression", "email_record_consent", "email_revoke_consent", "email_update_contact"];
export const INC2_NAMES = ["email_catalog_guard", "email_segments_versioning", "email_custom_value_is_valid",
  "email_contact_field_values_guard", "email_clean_label", "email_clean_description", "email_clean_uuid_batch",
  "email_is_uuid_text", "email_segment_invalid", "email_segment_validate", "email_segment_rule_matches",
  "email_segment_matches", "email_preview", "email_create_list", "email_archive_list", "email_add_list_members",
  "email_remove_list_members", "email_create_tag", "email_archive_tag", "email_add_contact_tags",
  "email_remove_contact_tags", "email_create_custom_field", "email_archive_custom_field", "email_set_contact_fields",
  "email_create_segment", "email_update_segment", "email_archive_segment", "email_preview_audience",
  "email_preview_segment", "email_import_contacts_from_crm"];
const RUNNER_FP_SQL = `
  select md5(coalesce(string_agg(n.nspname || '.' || p.proname || '(' || pg_catalog.pg_get_function_identity_arguments(p.oid) || '):'
           || md5(replace(p.prosrc, chr(13), '')) || ':' || p.prosecdef::text || ':' || coalesce(array_to_string(p.proconfig, ','), ''),
           '|' order by (n.nspname || '.' || p.proname || '(' || pg_catalog.pg_get_function_identity_arguments(p.oid) || ')') collate "C"), '')) as fp
  from pg_catalog.pg_proc p join pg_catalog.pg_namespace n on n.oid = p.pronamespace
  where n.nspname in ('public', 'private') and p.proname = any ($1)`;
export const STAGING_INC1_FP = "bea78511eb8edb8959f98dd7e835cc3b";
export const STAGING_INC2_FP = "a5c722084c60b6e4fe82eb57d0130b0c";
// Deliberate, documented change: only private.email_can differs.
export const EXPECTED_INC1_FP_AFTER_INC3A = "5615988a559e786c49aa88097238c72e";

export const OLD_TABLES = ["email_audit_log", "email_contacts", "email_contact_consents", "email_suppressions",
  "email_lists", "email_list_members", "email_tags", "email_contact_tags", "email_custom_field_definitions",
  "email_contact_field_values", "email_segments", "email_contact_crm_links"];
export const NEW_TABLES = ["email_sender_domains", "email_sender_identities", "email_templates", "email_template_versions"];

export function snapshots(db) {
  const all = async (sql, params = []) => (await db.query(sql, params)).rows;
  const one = async (sql, params = []) => (await db.query(sql, params)).rows[0];
  return {
    // pg_get_function_identity_arguments renders composite argument types
    // relative to search_path; the Staging run had no 'public' in it (types
    // render as public.email_contacts), so the fingerprint is taken likewise.
    fp: async (names) => {
      await db.exec("set search_path = ''");
      try {
        return (await one(RUNNER_FP_SQL, [names])).fp;
      } finally {
        await db.exec("reset search_path");
      }
    },
    functions: () => all(`
      select p.oid::regprocedure::text as sig, md5(p.prosrc) as src, p.prosecdef as definer,
             coalesce(array_to_string(p.proconfig, ','), '') as config, coalesce(p.proacl::text, '') as acl,
             pg_get_userbyid(p.proowner) as owner, p.provolatile as volatility
      from pg_proc p join pg_namespace n on n.oid = p.pronamespace
      where n.nspname in ('public', 'private') and p.proname like 'email\\_%' order by 1`),
    policies: () => all(`select tablename, policyname, cmd, roles::text as roles, qual, with_check
      from pg_policies where tablename like 'email\\_%' order by 1, 2`),
    tableAcl: () => all(`select relname, relacl::text as acl, relrowsecurity as rls from pg_class
      where relname like 'email\\_%' and relkind = 'r' order by 1`),
    tables: () => all(`select relname from pg_class c join pg_namespace n on n.oid = c.relnamespace
      where n.nspname = 'public' and c.relkind = 'r' and c.relname like 'email\\_%' order by 1`),
    constraints: () => all(`select conrelid::regclass::text as tbl, conname, pg_get_constraintdef(oid) as def
      from pg_constraint where conrelid::regclass::text like 'email\\_%' order by 1, 2`),
    triggers: () => all(`select tgrelid::regclass::text as tbl, tgname, tgfoid::regprocedure::text as fn,
        tgenabled, encode(tgargs, 'hex') as args
      from pg_trigger where not tgisinternal and tgrelid::regclass::text like 'email\\_%' order by 1, 2`),
    indexes: () => all(`select tablename, indexname, indexdef from pg_indexes
      where tablename like 'email\\_%' order by 1, 2`),
  };
}
