import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { addEdge, applyNodeChanges } from "@xyflow/react";
import { Archive, ArrowLeft, CheckCircle2, PanelLeftClose, PanelLeftOpen, Plus, Trash2, X } from "lucide-react";
import { Link, useNavigate, useParams, useSearchParams } from "react-router-dom";
import { BUILDER_NODE_TYPES, createsCycle, validateBuilderGraph } from "../model/builderGraph";
import { addGrowthEdge, addGrowthNode, deleteGrowthEdge, deleteGrowthNode, loadGrowthSystem, updateGrowthNode, updateGrowthSystem } from "../services/BuilderService";
import BuilderCanvas from "../components/BuilderCanvas";
import BuilderFlowList from "../components/BuilderFlowList";
import BuilderAssetBinding from "../components/BuilderAssetBinding";
import "../Builder.css";
import { readBuilderWorkspacePreferences, writeBuilderWorkspacePreferences } from "../model/builderWorkspacePreferences";

const toFlowNode = (node) => ({ id: node.id, type: "builder", position: { x: node.position_x, y: node.position_y }, data: node });
const toFlowEdge = (edge) => ({ id: edge.id, source: edge.source_node_id, target: edge.target_node_id, type: "smoothstep" });
export default function BuilderWorkspace() {
  const { systemId } = useParams(); const navigate = useNavigate(); const [search, setSearch] = useSearchParams();
  const [model, setModel] = useState(null); const [flowNodes, setFlowNodes] = useState([]); const [flowEdges, setFlowEdges] = useState([]); const [status, setStatus] = useState("saved"); const [error, setError] = useState("");
  const [paletteCollapsed, setPaletteCollapsed] = useState(() => readBuilderWorkspacePreferences().paletteCollapsed);
  const timers = useRef(new Map()); const queues = useRef(new Map());
  const selectedId = search.get("node"); const selected = model?.nodes.find((node) => node.id === selectedId) || null;
  const validation = useMemo(() => validateBuilderGraph(model?.nodes || [], model?.edges || []), [model]);
  const handleError = useCallback((value) => setError(value.message), []);
  const reload = useCallback(() => loadGrowthSystem(systemId).then((data) => { setModel(data); setFlowNodes(data.nodes.map(toFlowNode)); setFlowEdges(data.edges.map(toFlowEdge)); }).catch((value) => setError(value.message)), [systemId]);
  useEffect(() => { const activeTimers = timers.current; reload(); return () => { for (const timer of activeTimers.values()) clearTimeout(timer); }; }, [reload]);
  useEffect(() => { const warn = (event) => { if (status === "saving") { event.preventDefault(); event.returnValue = ""; } }; window.addEventListener("beforeunload", warn); return () => window.removeEventListener("beforeunload", warn); }, [status]);
  const enqueue = useCallback((key, operation) => { const next = (queues.current.get(key) || Promise.resolve()).then(operation); queues.current.set(key, next); setStatus("saving"); next.then(() => { if (queues.current.get(key) === next) setStatus("saved"); }).catch((value) => { setStatus("error"); setError(value.message.includes("0 rows") ? "El sistema cambió en otra sesión. Recarga antes de continuar." : value.message); }); return next; }, []);
  const persistPosition = useCallback((flowNode) => { clearTimeout(timers.current.get(flowNode.id)); setStatus("saving"); timers.current.set(flowNode.id, setTimeout(() => enqueue(flowNode.id, async () => { const current = model.nodes.find((node) => node.id === flowNode.id); const saved = await updateGrowthNode(current, { position_x: flowNode.position.x, position_y: flowNode.position.y }); setModel((value) => ({ ...value, nodes: value.nodes.map((node) => node.id === saved.id ? saved : node) })); }), 450)); }, [enqueue, model]);
  function onNodesChange(changes) { setFlowNodes((current) => { const next = applyNodeChanges(changes, current); for (const change of changes) if (change.type === "position" && change.dragging === false) { const node = next.find((item) => item.id === change.id); if (node) persistPosition(node); } return next; }); }
  async function addNode(nodeType) { setError(""); try { const definition = BUILDER_NODE_TYPES[nodeType]; const count = model.nodes.filter((node) => node.node_type === nodeType).length; const node = await addGrowthNode(model.revision, { node_type: nodeType, label: count ? `${definition.defaultLabel} ${count + 1}` : definition.defaultLabel, position_x: 80 + model.nodes.length * 210, position_y: 180, configuration: { config_version: 1 } }); setModel((value) => ({ ...value, nodes: [...value.nodes, node] })); setFlowNodes((value) => [...value, toFlowNode(node)]); setSearch({ node: node.id }); } catch (value) { setError(value.message); } }
  async function connect(connection) { const source = model.nodes.find((node) => node.id === connection.source); const target = model.nodes.find((node) => node.id === connection.target); const allowed = { traffic_source: ["landing_page"], landing_page: ["form"], form: ["lead_handoff"], lead_handoff: [] }; if (!source || !target || !allowed[source.node_type].includes(target.node_type)) return setError("Esa relación no corresponde al flujo Fuente → Landing → Formulario → Entrega."); if (createsCycle(model.edges, connection.source, connection.target)) return setError("Esa conexión crearía un ciclo, que no está permitido en V1."); try { const edge = await addGrowthEdge(model.revision, connection.source, connection.target); setModel((value) => ({ ...value, edges: [...value.edges, edge] })); setFlowEdges((value) => addEdge(toFlowEdge(edge), value)); } catch (value) { setError(value.message); } }
  async function removeEdges(edges) { for (const edge of edges) await deleteGrowthEdge(edge.id); const ids = new Set(edges.map((edge) => edge.id)); setModel((value) => ({ ...value, edges: value.edges.filter((edge) => !ids.has(edge.id)) })); }
  function selectNode(id) { const node = model.nodes.find((item) => item.id === id); setSearch(node?.asset_id ? { node: id, asset: node.asset_id } : { node: id }); }
  function replaceNode(saved) { setModel((value) => ({ ...value, nodes: value.nodes.map((node) => node.id === saved.id ? saved : node) })); setFlowNodes((value) => value.map((node) => node.id === saved.id ? { ...node, data: saved } : node)); setSearch(saved.asset_id ? { node: saved.id, asset: saved.asset_id } : { node: saved.id }); }
  async function updateSelected(changes) { try { const saved = await updateGrowthNode(selected, changes); replaceNode(saved); } catch (value) { setError(value.message); } }
  async function removeSelected() { await deleteGrowthNode(selected.id); setModel((value) => ({ ...value, nodes: value.nodes.filter((node) => node.id !== selected.id), edges: value.edges.filter((edge) => edge.source_node_id !== selected.id && edge.target_node_id !== selected.id) })); setFlowNodes((value) => value.filter((node) => node.id !== selected.id)); setFlowEdges((value) => value.filter((edge) => edge.source !== selected.id && edge.target !== selected.id)); setSearch({}); }
  async function markReady() { if (!validation.valid) return setError("Corrige la estructura antes de marcar el sistema como listo."); const system = await updateGrowthSystem(systemId, { lifecycle: "ready" }); setModel((value) => ({ ...value, system })); }
  async function archive() { await updateGrowthSystem(systemId, { lifecycle: "archived", archived_at: new Date().toISOString() }); navigate("/construir"); }
  function togglePalette() { const next = !paletteCollapsed; setPaletteCollapsed(next); writeBuilderWorkspacePreferences({ ...readBuilderWorkspacePreferences(), paletteCollapsed: next }); }
  if (!model) return <div className="builder-loading">{error || "Cargando sistema…"}</div>;
  return <div className="builder-workspace"><header className="builder-workspace-head"><Link to="/construir" aria-label="Volver a Builder" onClick={(event) => { if (status === "saving") { event.preventDefault(); setError("Espera a que finalice el guardado antes de salir."); } }}><ArrowLeft/></Link><div><span>BUILDER · {model.system.lifecycle === "ready" ? "LISTO" : "BORRADOR"}</span><h1>{model.system.name}</h1><p>{model.system.objective}</p></div><div className="builder-head-actions"><small className={`builder-save-state ${status}`}>{status === "saving" ? "Guardando…" : status === "error" ? "Error al guardar" : "Guardado"}</small><button onClick={markReady} disabled={status === "saving" || !validation.valid || model.system.lifecycle === "ready"}><CheckCircle2 size={16}/> Marcar listo</button><button aria-label="Archivar sistema" onClick={archive} disabled={status === "saving"}><Archive size={16}/></button></div></header>
    {error && <div className="builder-workspace-error" role="alert">{error}<button onClick={() => setError("")}><X size={15}/></button></div>}
    <div className={`builder-workspace-body ${paletteCollapsed ? "palette-collapsed" : ""}`}><aside className="builder-palette"><div className="builder-palette-head"><span>Agregar paso</span><button type="button" onClick={togglePalette} aria-label={paletteCollapsed ? "Expandir paleta" : "Contraer paleta"} aria-expanded={!paletteCollapsed} title={paletteCollapsed ? "Expandir paleta" : "Contraer paleta"}>{paletteCollapsed ? <PanelLeftOpen size={16}/> : <PanelLeftClose size={16}/>}</button></div>{Object.entries(BUILDER_NODE_TYPES).map(([key, item]) => <button key={key} onClick={() => addNode(key)} title={paletteCollapsed ? item.label : undefined}><Plus size={15}/><span>{item.label}</span></button>)}<div className="builder-validation"><strong>{validation.valid ? "Estructura válida" : `${validation.errors.length} ajustes pendientes`}</strong>{validation.errors.slice(0, 4).map((item, index) => <p key={`${item.code}-${index}`}>{item.message}</p>)}</div></aside>
      <main><BuilderCanvas nodes={flowNodes} edges={flowEdges} onNodesChange={onNodesChange} onConnect={connect} onNodeClick={selectNode} onEdgesDelete={removeEdges} layoutKey={`${paletteCollapsed}-${Boolean(selected)}`}/><BuilderFlowList nodes={model.nodes} edges={model.edges} onSelect={selectNode} onConnect={connect}/></main>
      {selected && <aside className="builder-inspector" aria-label="Inspector del paso"><div><span>Configuración</span><button onClick={() => setSearch({})} aria-label="Cerrar inspector"><X/></button></div><small>{BUILDER_NODE_TYPES[selected.node_type].label}</small><label>Nombre<input value={selected.label} maxLength={120} onChange={(event) => setModel((value) => ({ ...value, nodes: value.nodes.map((node) => node.id === selected.id ? { ...node, label: event.target.value } : node) }))} onBlur={(event) => updateSelected({ label: event.target.value.trim() })}/></label>{(selected.node_type === "landing_page" || selected.node_type === "form") && <BuilderAssetBinding node={selected} onNodeUpdated={replaceNode} onError={handleError}/>}<button className="builder-delete" onClick={removeSelected}><Trash2 size={16}/> Eliminar paso</button></aside>}
    </div>
  </div>;
}
