import { useEffect, useRef, useState } from "react";
import { Check, ChevronDown, Circle, Download, ExternalLink, FileText, Image, Plus, Trash2, Upload, X } from "lucide-react";
import {
  createTaskEvidenceRequirement,
  deleteTaskEvidence,
  deleteTaskEvidenceRequirement,
  downloadTaskEvidence,
  getTaskEvidencePreviewUrl,
  openTaskEvidence,
  submitTaskEvidenceFile,
  submitTaskEvidenceValue,
  updateTaskEvidenceRequirement,
} from "../../services/ProjectService";
import { blankEvidenceRequirement, evidenceTypeDefaults, evidenceTypeHints, evidenceTypeLabels, validateEvidenceRequirement } from "./taskEvidenceConfig";

const field = "min-w-0 rounded-lg border border-zinc-800 bg-zinc-950 px-3 py-2 text-sm text-white outline-none focus:border-zinc-500 focus:ring-1 focus:ring-zinc-600";

export function EvidenceRequirementFields({ value, onChange, onRemove, error = "" }) {
  function changeType(evidenceType) { onChange({ ...value, evidence_type: evidenceType, ...evidenceTypeDefaults[evidenceType] }); }
  return <div className="grid min-w-0 gap-3 rounded-xl border border-zinc-800 bg-zinc-950/60 p-3 sm:grid-cols-2">
    <label className="min-w-0 sm:col-span-2"><span className="mb-1 block text-xs text-zinc-400">Nombre</span><input required minLength={2} maxLength={120} className={`${field} w-full`} placeholder="Ej. Foto después" value={value.label} onChange={(event) => onChange({ ...value, label: event.target.value })} /></label>
    <label className="min-w-0"><span className="mb-1 block text-xs text-zinc-400">Tipo</span><select className={`${field} w-full`} value={value.evidence_type} onChange={(event) => changeType(event.target.value)}>{Object.entries(evidenceTypeLabels).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select><span className="mt-1 block text-[11px] text-zinc-600">{evidenceTypeHints[value.evidence_type]}</span></label>
    <label className="flex min-h-11 items-center gap-2 rounded-lg border border-zinc-800 px-3 text-sm text-zinc-300"><input type="checkbox" checked={value.is_required} onChange={(event) => onChange({ ...value, is_required: event.target.checked, min_count: event.target.checked ? Math.max(1, value.min_count) : 0 })} /> Obligatorio</label>
    <label className="text-xs text-zinc-500">Mínimo<input type="number" min="0" max="20" disabled={!value.is_required} className={`${field} mt-1 w-full`} value={value.min_count} onChange={(event) => onChange({ ...value, min_count: Number(event.target.value) })} /></label>
    <label className="text-xs text-zinc-500">Máximo<input type="number" min="1" max="20" className={`${field} mt-1 w-full`} value={value.max_count} onChange={(event) => onChange({ ...value, max_count: Number(event.target.value) })} /></label>
    <label className="min-w-0 sm:col-span-2"><span className="mb-1 block text-xs text-zinc-400">Descripción opcional</span><textarea maxLength={1000} rows={2} className={`${field} w-full resize-y`} placeholder="Explica qué debe demostrar esta evidencia" value={value.description} onChange={(event) => onChange({ ...value, description: event.target.value })} /></label>
    {error && <p role="alert" className="text-xs text-red-300 sm:col-span-2">{error}</p>}
    {onRemove && <button type="button" onClick={onRemove} className="inline-flex items-center gap-2 text-xs text-zinc-500 hover:text-red-300"><Trash2 size={14} /> Quitar requisito</button>}
  </div>;
}

export default function TaskEvidencePanel({ task, projectId, organizationId, userId, canManage, canSubmit, onChange, reportError }) {
  const [open, setOpen] = useState(false);
  const [draft, setDraft] = useState(blankEvidenceRequirement());
  const [draftError, setDraftError] = useState("");
  const requirements = task.evidence_requirements || [];
  const required = requirements.filter((item) => item.is_required);
  const fulfilled = required.filter((item) => item.evidence.length >= item.min_count);
  const complete = fulfilled.length === required.length;
  const stateLabel = !requirements.length ? "No requiere evidencia" : task.status === "completed" ? "Evidencia verificada para finalización" : complete ? "Evidencia completa" : "Evidencia pendiente";

  async function act(operation) { try { reportError(""); await operation(); await onChange(); return true; } catch (reason) { reportError(reason.message || "No se pudo completar la acción."); return false; } }
  async function addRequirement(event) {
    event.preventDefault(); const validation = validateEvidenceRequirement(draft); setDraftError(validation); if (validation) return;
    if (await act(() => createTaskEvidenceRequirement(task.id, { ...draft, position: requirements.length }, userId))) setDraft(blankEvidenceRequirement());
  }

  return <div className="min-w-0 sm:col-start-2 sm:col-span-2">
    <button type="button" aria-expanded={open} onClick={() => setOpen((value) => !value)} className="flex w-full min-w-0 items-center justify-between gap-3 rounded-xl border border-zinc-800 bg-zinc-950/70 px-3 py-2.5 text-left">
      <span className="min-w-0"><span className={`block text-xs font-medium ${complete ? "text-emerald-300" : "text-amber-300"}`}>{stateLabel}</span>{required.length > 0 && <span className="mt-0.5 block text-[11px] text-zinc-500">{fulfilled.length} / {required.length} requisitos obligatorios</span>}</span>
      <ChevronDown size={16} className={`shrink-0 text-zinc-500 transition-transform ${open ? "rotate-180" : ""}`} />
    </button>
    {!complete && <div className="mt-2 rounded-lg border border-amber-900/40 bg-amber-950/15 px-3 py-2 text-xs text-amber-200"><strong>Falta evidencia obligatoria:</strong><ul className="mt-1 list-disc space-y-0.5 pl-4">{required.filter((item) => item.evidence.length < item.min_count).map((item) => <li key={item.id}>{item.label} — {item.evidence.length} de {item.min_count}</li>)}</ul></div>}
    {open && <div className="mt-2 space-y-3 rounded-xl border border-zinc-800 p-3 sm:p-4">
      {task.status === "completed" && <div className="rounded-xl border border-emerald-900/40 bg-emerald-950/15 p-3"><p className="text-sm font-medium text-emerald-200">Tarea completada</p><p className="mt-1 text-xs text-zinc-400">La evidencia utilizada para completar esta tarea está bloqueada. Reabre la tarea para realizar cambios.</p></div>}
      {!requirements.length && <p className="text-sm text-zinc-500">Esta tarea puede completarse sin evidencia.</p>}
      {requirements.map((requirement) => <Requirement key={requirement.id} requirement={requirement} task={task} projectId={projectId} organizationId={organizationId} userId={userId} canManage={canManage} canSubmit={canSubmit} onChange={onChange} reportError={reportError} />)}
      {canManage && task.status !== "completed" && <form onSubmit={addRequirement} className="space-y-2 border-t border-zinc-800 pt-3"><p className="text-sm font-medium text-zinc-300">Añadir requisito</p><EvidenceRequirementFields value={draft} onChange={(next) => { setDraft(next); setDraftError(""); }} error={draftError} /><button className="inline-flex min-h-10 items-center gap-2 rounded-lg border border-zinc-700 px-3 py-2 text-xs text-white hover:border-zinc-500"><Plus size={14} /> Guardar requisito</button></form>}
    </div>}
  </div>;
}

function Requirement({ requirement, task, projectId, organizationId, userId, canManage, canSubmit, onChange, reportError }) {
  const inputRef = useRef(null); const [value, setValue] = useState(""); const [uploads, setUploads] = useState([]); const [editing, setEditing] = useState(null); const [editError, setEditError] = useState(""); const [savingValue, setSavingValue] = useState(false);
  const fulfilled = !requirement.is_required || requirement.evidence.length >= requirement.min_count; const atMax = requirement.evidence.length >= requirement.max_count;
  async function act(operation) { try { reportError(""); await operation(); await onChange(); return true; } catch (reason) { reportError(reason.message || "No se pudo completar la evidencia."); return false; } }
  async function sendValue(event) { event.preventDefault(); if (!value.trim() || savingValue) return; setSavingValue(true); if (await act(() => submitTaskEvidenceValue({ taskId: task.id, requirement, value, userId }))) setValue(""); setSavingValue(false); }
  async function sendFiles(event) {
    const remaining = Math.max(0, requirement.max_count - requirement.evidence.length); const files = Array.from(event.target.files || []).slice(0, remaining); event.target.value = "";
    const batch = files.map((file) => ({ id: crypto.randomUUID(), file, name: file.name, progress: 0, status: "Preparando", error: "" })); setUploads(batch);
    for (const item of batch) { try { await submitTaskEvidenceFile({ projectId, organizationId, taskId: task.id, requirement, file: item.file, userId, onProgress: (progress, status) => setUploads((rows) => rows.map((row) => row.id === item.id ? { ...row, progress, status } : row)) }); setUploads((rows) => rows.map((row) => row.id === item.id ? { ...row, progress: 100, status: "Completado" } : row)); await onChange(); } catch (reason) { setUploads((rows) => rows.map((row) => row.id === item.id ? { ...row, status: "Error", error: reason.message || "No se pudo subir." } : row)); } }
  }
  async function saveEdit(event) { event.preventDefault(); const validation = validateEvidenceRequirement(editing); setEditError(validation); if (validation) return; if (await act(() => updateTaskEvidenceRequirement(requirement.id, { evidence_type: editing.evidence_type, label: editing.label.trim(), description: editing.description?.trim() || null, is_required: editing.is_required, min_count: editing.is_required ? Number(editing.min_count) : 0, max_count: Number(editing.max_count) }))) setEditing(null); }
  const fileAccept = requirement.evidence_type === "image" ? "image/jpeg,image/png,image/webp" : requirement.evidence_type === "video" ? "video/mp4,video/webm" : ".pdf,.doc,.docx,.xls,.xlsx,.ppt,.pptx,.csv,.txt";
  return <article className={`min-w-0 rounded-xl border p-3 ${fulfilled ? "border-zinc-800" : "border-amber-900/50"}`}>
    <div className="flex min-w-0 items-start gap-3">{fulfilled ? <Check aria-label="Cumplido" size={18} className="mt-0.5 shrink-0 text-emerald-300" /> : <Circle aria-label="Pendiente" size={18} className="mt-0.5 shrink-0 text-amber-300" />}<div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="break-words text-sm font-medium text-white">{requirement.label}</p><span className={`rounded-full px-2 py-0.5 text-[10px] ${requirement.is_required ? "bg-zinc-800 text-zinc-300" : "bg-blue-950/50 text-blue-300"}`}>{requirement.is_required ? (fulfilled ? "Cumplido" : "Pendiente") : "Opcional"}</span>{atMax && <span className="rounded-full bg-amber-950/40 px-2 py-0.5 text-[10px] text-amber-300">Límite alcanzado</span>}</div><p className="mt-1 text-xs text-zinc-500">{evidenceTypeLabels[requirement.evidence_type]} · {requirement.evidence.length} / {requirement.is_required ? requirement.min_count : requirement.max_count}{requirement.description ? ` · ${requirement.description}` : ""}</p><div className="mt-2 h-1 overflow-hidden rounded-full bg-zinc-800"><div className={`h-full ${fulfilled ? "bg-emerald-400" : "bg-amber-400"}`} style={{ width: `${Math.min(100, (requirement.evidence.length / Math.max(1, requirement.is_required ? requirement.min_count : requirement.max_count)) * 100)}%` }} /></div></div>{canManage && task.status !== "completed" && !requirement.evidence.length && <button type="button" aria-label={`Eliminar requisito ${requirement.label}`} onClick={() => window.confirm("¿Eliminar este requisito?") && act(() => deleteTaskEvidenceRequirement(requirement.id))} className="shrink-0 p-1 text-zinc-600 hover:text-red-300"><Trash2 size={15} /></button>}</div>
    <div className="mt-3 space-y-2">{requirement.evidence.map((evidence) => <EvidenceItem key={evidence.id} evidence={evidence} canDelete={task.status !== "completed" && canSubmit && (canManage || evidence.submitted_by === userId)} onDelete={() => window.confirm("¿Retirar esta evidencia?") && act(() => deleteTaskEvidence(evidence))} reportError={reportError} />)}</div>
    {canManage && task.status !== "completed" && <div className="mt-3 border-t border-zinc-800 pt-2">{editing ? <form onSubmit={saveEdit} className="space-y-2"><p className="text-xs font-medium text-zinc-300">Editando “{requirement.label}”</p><EvidenceRequirementFields value={editing} onChange={(next) => { setEditing(next); setEditError(""); }} error={editError} /><div className="flex flex-wrap gap-2"><button className="rounded-lg border border-zinc-700 px-3 py-2 text-xs text-white">Guardar cambios</button><button type="button" onClick={() => setEditing(null)} className="px-3 py-2 text-xs text-zinc-500">Cancelar</button></div></form> : <button type="button" onClick={() => setEditing({ ...requirement })} className="text-xs text-zinc-500 hover:text-white">Editar requisito</button>}</div>}
    {!atMax && task.status !== "completed" && canSubmit && <div className="mt-3">{["url", "text"].includes(requirement.evidence_type) ? <form onSubmit={sendValue} className="flex min-w-0 flex-col gap-2 sm:flex-row">{requirement.evidence_type === "text" ? <textarea aria-label={`Texto para ${requirement.label}`} required maxLength={5000} rows={2} className={`${field} min-w-0 flex-1 resize-y`} placeholder="Escribe la evidencia" value={value} onChange={(event) => setValue(event.target.value)} /> : <input aria-label={`Enlace para ${requirement.label}`} required type="url" pattern="https://.*" maxLength={2000} className={`${field} min-w-0 flex-1`} placeholder="https://" value={value} onChange={(event) => setValue(event.target.value)} />}<button disabled={savingValue} className="min-h-10 rounded-lg border border-zinc-700 px-3 py-2 text-xs text-white disabled:opacity-50">{savingValue ? "Guardando…" : "Guardar"}</button></form> : <><input ref={inputRef} aria-label={`Archivos para ${requirement.label}`} type="file" multiple className="hidden" accept={fileAccept} onChange={sendFiles} /><button type="button" onClick={() => inputRef.current?.click()} className="inline-flex min-h-10 items-center gap-2 rounded-lg border border-zinc-700 px-3 py-2 text-xs text-white"><Upload size={14} /> Subir evidencia</button>{requirement.evidence_type === "image" && <p className="mt-1 text-[11px] text-zinc-600">En móvil puedes usar cámara o galería.</p>}{uploads.length > 0 && <div className="mt-2 space-y-2">{uploads.map((item) => <div key={item.id}><div className="flex min-w-0 justify-between gap-3 text-xs"><span className="min-w-0 truncate text-zinc-400">{item.name}</span><span className={item.error ? "text-red-300" : "text-zinc-500"}>{item.status}</span></div><div className="mt-1 h-1 overflow-hidden rounded-full bg-zinc-800"><div className={`h-full ${item.error ? "bg-red-400" : "bg-white"}`} style={{ width: `${item.progress}%` }} /></div>{item.error && <p className="mt-1 text-xs text-red-300">{item.error}</p>}</div>)}</div>}</>}</div>}
  </article>;
}

function EvidenceItem({ evidence, canDelete, onDelete, reportError }) {
  const [previewUrl, setPreviewUrl] = useState(""); const [modal, setModal] = useState(false); const [expanded, setExpanded] = useState(false);
  useEffect(() => { let active = true; if (evidence.evidence_type === "image") getTaskEvidencePreviewUrl(evidence).then((url) => { if (active) setPreviewUrl(url); }).catch(() => {}); return () => { active = false; }; }, [evidence]);
  async function preview() { try { const url = previewUrl || await getTaskEvidencePreviewUrl(evidence); setPreviewUrl(url); setModal(true); } catch (reason) { reportError(reason.message); } }
  async function download() { try { await downloadTaskEvidence(evidence); } catch (reason) { reportError(reason.message); } }
  const isPdf = evidence.mime_type === "application/pdf"; const previewable = ["image", "video"].includes(evidence.evidence_type) || isPdf;
  return <div className="min-w-0 rounded-lg bg-zinc-950 p-2.5"><div className="flex min-w-0 items-start gap-3">{evidence.evidence_type === "image" && previewUrl ? <button type="button" aria-label={`Vista previa de ${evidence.file_name}`} onClick={preview} className="h-14 w-14 shrink-0 overflow-hidden rounded-lg border border-zinc-800"><img src={previewUrl} alt={`Miniatura de ${evidence.file_name}`} className="h-full w-full object-cover" /></button> : <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-lg border border-zinc-800 text-zinc-500">{evidence.evidence_type === "image" ? <Image size={17} /> : <FileText size={17} />}</div>}<div className="min-w-0 flex-1">{evidence.value_text ? <><p className={`whitespace-pre-wrap break-words text-xs leading-5 text-zinc-300 ${expanded ? "" : "line-clamp-3"}`}>{evidence.value_text}</p>{evidence.value_text.length > 180 && <button type="button" onClick={() => setExpanded((value) => !value)} className="mt-1 text-xs text-zinc-500">{expanded ? "Ver menos" : "Ver más"}</button>}</> : evidence.value_url ? <><p className="truncate text-xs text-zinc-300" title={evidence.value_url}>{safeHostname(evidence.value_url)}</p><p className="mt-1 truncate text-[11px] text-zinc-600" title={evidence.value_url}>{evidence.value_url}</p></> : <><p className="truncate text-xs font-medium text-zinc-300" title={evidence.file_name}>{evidence.file_name}</p><p className="mt-1 text-[11px] text-zinc-600">{formatBytes(evidence.size_bytes)} · {evidence.submitter?.first_name || "Usuario"}</p></>}</div><div className="flex shrink-0 flex-wrap justify-end gap-1">{evidence.value_url && <button type="button" aria-label="Abrir enlace" onClick={() => openTaskEvidence(evidence)} className="rounded-md p-2 text-zinc-400 hover:bg-zinc-800"><ExternalLink size={14} /></button>}{previewable && <button type="button" aria-label={`Previsualizar ${evidence.file_name}`} onClick={preview} className="rounded-md p-2 text-zinc-400 hover:bg-zinc-800"><ExternalLink size={14} /></button>}{evidence.storage_path && <button type="button" aria-label={`Descargar ${evidence.file_name}`} onClick={download} className="rounded-md p-2 text-zinc-400 hover:bg-zinc-800"><Download size={14} /></button>}{canDelete && <button type="button" aria-label="Retirar evidencia" onClick={onDelete} className="rounded-md p-2 text-zinc-600 hover:bg-red-950/30 hover:text-red-300"><Trash2 size={14} /></button>}</div></div>{modal && <PreviewModal evidence={evidence} url={previewUrl} onClose={() => setModal(false)} />}</div>;
}

function PreviewModal({ evidence, url, onClose }) { return <div role="dialog" aria-modal="true" aria-label={`Vista previa de ${evidence.file_name}`} className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 p-3" onClick={onClose}><div className="relative max-h-[90vh] w-full max-w-4xl overflow-hidden rounded-2xl border border-zinc-700 bg-zinc-950 p-3" onClick={(event) => event.stopPropagation()}><button type="button" aria-label="Cerrar vista previa" onClick={onClose} className="absolute right-4 top-4 z-10 rounded-full bg-black/70 p-2 text-white"><X size={18} /></button>{evidence.evidence_type === "image" ? <img src={url} alt={evidence.file_name} className="mx-auto max-h-[82vh] max-w-full object-contain" /> : evidence.evidence_type === "video" ? <video src={url} controls className="mx-auto max-h-[82vh] max-w-full" /> : <iframe src={url} title={`PDF ${evidence.file_name}`} className="h-[82vh] w-full bg-white" />}</div></div>; }
function formatBytes(value) { const bytes = Number(value || 0); if (bytes < 1024) return `${bytes} B`; if (bytes < 1048576) return `${(bytes / 1024).toFixed(1)} KB`; return `${(bytes / 1048576).toFixed(1)} MB`; }
function safeHostname(value) { try { return new URL(value).hostname; } catch { return "Enlace"; } }
