import { ArrowDown, ArrowUp, Pencil, Plus, Save, X } from "lucide-react";
import { useEffect, useState } from "react";
import Card from "../../components/ui/Card";
import { useAuth } from "../../Context/AuthContext";
import { createDivision, getDivisions, reorderDivisions, setDivisionActive, updateDivision } from "../../services/DivisionService";

export default function DivisionsSettings() {
  const { organization } = useAuth();
  const [divisions, setDivisions] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [message, setMessage] = useState(""); const [editing, setEditing] = useState(null); const [creating, setCreating] = useState(false); const [saving, setSaving] = useState(false);
  async function load() { setLoading(true); setError(""); try { setDivisions(await getDivisions(organization.id, { includeInactive: true })); } catch (reason) { setError(reason.message); } finally { setLoading(false); } }
  useEffect(() => {
    let active = true;
    if (!organization?.id) return undefined;
    getDivisions(organization.id, { includeInactive: true })
      .then((rows) => { if (active) setDivisions(rows); })
      .catch((reason) => { if (active) setError(reason.message); })
      .finally(() => { if (active) setLoading(false); });
    return () => { active = false; };
  }, [organization?.id]);
  async function toggle(division) { const action = division.active ? "desactivar" : "activar"; if (!window.confirm(`¿Quieres ${action} la división “${division.name}”?`)) return; setSaving(true); setError(""); try { await setDivisionActive(division.id, !division.active); setMessage(`División ${division.active ? "desactivada" : "activada"}.`); await load(); } catch (reason) { setError(reason.message); } finally { setSaving(false); } }
  async function move(index, delta) { const next = [...divisions]; const target = index + delta; if (target < 0 || target >= next.length) return; [next[index], next[target]] = [next[target], next[index]]; setDivisions(next); setSaving(true); setError(""); try { await reorderDivisions(next); setMessage("Orden de divisiones actualizado."); } catch (reason) { setError(reason.message); await load(); } finally { setSaving(false); } }
  async function save(form) { setSaving(true); setError(""); try { if (editing) { await updateDivision(editing.id, form); setMessage("División actualizada."); } else { await createDivision(organization.id, { ...form, position: divisions.length }); setMessage("División creada."); } setEditing(null); setCreating(false); await load(); } catch (reason) { setError(reason.code === "23505" ? "Ya existe una división con ese nombre o identificador." : reason.message); } finally { setSaving(false); } }
  if (loading) return <Card hover={false} contentClassName="p-8"><p className="text-zinc-500">Cargando divisiones...</p></Card>;
  return <div className="min-w-0 space-y-5"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><p className="max-w-2xl text-sm leading-6 text-zinc-400">Las divisiones inactivas permanecen visibles para conservar el contexto histórico. No existe eliminación física en esta pantalla.</p><button onClick={() => { setEditing(null); setCreating(true); }} className="inline-flex items-center justify-center gap-2 rounded-xl bg-white px-5 py-3 font-medium text-black"><Plus size={17} /> Nueva división</button></div>{error && <div className="rounded-xl border border-red-900 bg-red-950/20 px-4 py-3 text-sm text-red-300">{error}</div>}{message && <div className="rounded-xl border border-zinc-700 bg-zinc-900 px-4 py-3 text-sm text-zinc-200" role="status">{message}</div>}{(creating || editing) && <DivisionForm division={editing} saving={saving} onSave={save} onClose={() => { setEditing(null); setCreating(false); }} />}<div className="space-y-3">{divisions.map((division, index) => <Card key={division.id} hover={false} contentClassName="p-4 sm:p-5"><div className="flex min-w-0 flex-col gap-4 sm:flex-row sm:items-center"><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="break-words font-semibold text-white">{division.name}</h3><span className={`rounded-full px-2 py-1 text-xs ${division.active ? "bg-emerald-950 text-emerald-300" : "bg-zinc-800 text-zinc-400"}`}>{division.active ? "Activa" : "Inactiva"}</span></div>{division.description && <p className="mt-2 text-sm leading-6 text-zinc-400">{division.description}</p>}<p className="mt-2 break-all text-xs text-zinc-600">{division.slug}</p></div><div className="flex flex-wrap items-center gap-2"><button disabled={saving || index === 0} onClick={() => move(index, -1)} aria-label={`Subir ${division.name}`} className="rounded-lg border border-zinc-700 p-2 text-zinc-300 disabled:opacity-30"><ArrowUp size={16} /></button><button disabled={saving || index === divisions.length - 1} onClick={() => move(index, 1)} aria-label={`Bajar ${division.name}`} className="rounded-lg border border-zinc-700 p-2 text-zinc-300 disabled:opacity-30"><ArrowDown size={16} /></button><button onClick={() => { setCreating(false); setEditing(division); }} className="inline-flex items-center gap-2 rounded-lg border border-zinc-700 px-3 py-2 text-sm text-zinc-300"><Pencil size={15} /> Editar</button><button disabled={saving} onClick={() => toggle(division)} className={`rounded-lg border px-3 py-2 text-sm ${division.active ? "border-amber-800 text-amber-300" : "border-emerald-800 text-emerald-300"}`}>{division.active ? "Desactivar" : "Activar"}</button></div></div></Card>)}{!divisions.length && <Card hover={false} contentClassName="p-8 text-center"><p className="text-zinc-500">No hay divisiones configuradas.</p></Card>}</div></div>;
}

function DivisionForm({ division, saving, onSave, onClose }) { const [form, setForm] = useState({ name: division?.name || "", description: division?.description || "" }); return <Card hover={false} contentClassName="p-5 sm:p-6"><form onSubmit={(event) => { event.preventDefault(); onSave(form); }}><div className="flex items-center justify-between gap-4"><h2 className="text-lg font-semibold text-white">{division ? "Editar división" : "Nueva división"}</h2><button type="button" onClick={onClose} className="p-2 text-zinc-400"><X size={19} /></button></div><div className="mt-5 grid gap-4"><label><span className="mb-2 block text-sm text-zinc-400">Nombre</span><input required minLength={2} maxLength={100} className="field" value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} /></label><label><span className="mb-2 block text-sm text-zinc-400">Descripción</span><textarea rows={3} className="field resize-y" value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} /></label></div>{division && <p className="mt-3 text-xs text-zinc-500">El identificador técnico no se modifica al cambiar el nombre.</p>}<button disabled={saving} className="mt-5 inline-flex w-full items-center justify-center gap-2 rounded-xl bg-white px-5 py-3 font-medium text-black disabled:opacity-50 sm:w-auto"><Save size={17} /> {saving ? "Guardando..." : "Guardar división"}</button></form></Card>; }
